#!/bin/bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE impress;
    CREATE DATABASE meet;
    CREATE DATABASE dictaphone;
    CREATE DATABASE keycloak;
    GRANT ALL PRIVILEGES ON DATABASE impress TO ${POSTGRES_USER};
    GRANT ALL PRIVILEGES ON DATABASE meet TO ${POSTGRES_USER};
    GRANT ALL PRIVILEGES ON DATABASE dictaphone TO ${POSTGRES_USER};
    GRANT ALL PRIVILEGES ON DATABASE keycloak TO ${POSTGRES_USER};
EOSQL
